
version: 2

models:
  - name: silver_local_bike__brands
    columns:
      - name: brand_id
        tests:
          - unique
          - not_null
      - name: brand_name
  - name: silver_local_bike__categories
    columns:
      - name: category_id
        tests:
          - unique
          - not_null
      - name: category_name
  - name: silver_local_bike__customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: customer_first_name
      - name: customer_last_name
      - name: customer_email
      - name: customer_phone
      - name: customer_street
      - name: customer_zip_code
      - name: customer_city
      - name: customer_state
  - name: silver_local_bike__orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - relationships:
              name: customer_id_foreign_key_in_silver_local_bike__orders
              arguments:
                to: ref('silver_local_bike__customers')
                field: customer_id
      - name: staff_id
        tests:
          - relationships:
              name: staff_id_foreign_key_in_silver_local_bike__orders
              arguments:
                to: ref('silver_local_bike__staffs')
                field: staff_id
      - name: store_id
        tests:
          - relationships:
              name: store_id_foreign_key_in_silver_local_bike__orders
              arguments:
                to: ref('silver_local_bike__stores')
                field: store_id
      - name: order_placed_at
      - name: order_required_at
      - name: order_shipped_at
      - name: order_status
  - name: silver_local_bike__order_items
    columns:
      - name: order_item_id
        tests:
          - not_null
      - name: order_id
        tests:
          - relationships:
              name: order_id_foreign_key_in_silver_local_bike__order_items
              arguments:
                to: ref('silver_local_bike__orders')
                field: order_id
      - name: product_id
        tests:
          - relationships:
              name: product_id_foreign_key_in_silver_local_bike__order_items
              arguments:
                to: ref('silver_local_bike__products')
                field: product_id
      - name: order_item_price
      - name: order_item_quantity
      - name: order_item_discount
  - name: silver_local_bike__products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: category_id
        tests:
          - relationships:
              name: category_id_foreign_key_in_silver_local_bike__products
              arguments:
                to: ref('silver_local_bike__categories')
                field: category_id
      - name: brand_id
        tests:
          - relationships:
              name: brand_id_foreign_key_in_silver_local_bike__products
              arguments:
                to: ref('silver_local_bike__brands')
                field: brand_id
      - name: product_name
      - name: product_price
      - name: product_model_year



