
version: 2

models:
  - name: silver_local_bike__brands
    description: "This model list brands."
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brand."
        tests:
            - unique
            - not_null
      - name: brand_name
        description: "The name of the brand."



